
-- Vehicle definition

CREATE TABLE Vehicle (
	VID INTEGER PRIMARY KEY AUTOINCREMENT,
	VIN TEXT,
	MMID INTEGER,
	FirstDt DateTime DEFAULT (DateTime()),
	CDCID TEXT);

CREATE TABLE MakeModel (
	MMID INTEGER PRIMARY KEY AUTOINCREMENT,
	Make TEXT,
	Model TEXT
);

CREATE TABLE ScrapLog (
	SLID INTEGER PRIMARY KEY AUTOINCREMENT,
	InsertDate DATETIME DEFAULT (datetime()),
	MMID INTEGER,
	VID INTEGER
);

CREATE TABLE ScrapMeta (
	SMID INTEGER PRIMARY KEY AUTOINCREMENT,
	SLID INTEGER,
	TagName TEXT,
	TagValue TEXT
);

CREATE TABLE MMTrim (
	MMTID INTEGER PRIMARY KEY AUTOINCREMENT,
	MMID INTEGER,
	CDCmake TEXT,
	CDCmodel TEXT,
	CDCtrim TEXT
);