
-- Vehicle definition

CREATE TABLE Vehicle (
	VID INTEGER PRIMARY KEY AUTOINCREMENT,
	VIN TEXT,
	MMTID INTEGER, 
	FirstDt DateTime DEFAULT (DateTime()), 
	CDCID TEXT, 
	LastScrapDt Datetime, 
	IsActive INTEGER DEFAULT (1)
);

CREATE TABLE MakeModel (
	MMID INTEGER PRIMARY KEY AUTOINCREMENT,
	CDCmake TEXT,
	CDCmodel TEXT,
	minYr INTEGER,
	maxYr INTEGER
);

CREATE TABLE ScrapLog (
	SLID INTEGER PRIMARY KEY AUTOINCREMENT,
	InsertDate DATETIME DEFAULT (datetime()),
	MMTID INTEGER, 
	VID INTEGER, 
	LogDoneDt DateTime, 
	IDsDoneDt DateTime
);

CREATE TABLE ScrapMeta (
	SMID INTEGER PRIMARY KEY AUTOINCREMENT,
	InsertDate Datetime DEFAULT (Datetime()),
	VID INTEGER,
	TagName TEXT,
	TagValue TEXT, 
	SLID INTEGER
);

CREATE TABLE MMTrim (
	MMTID INTEGER PRIMARY KEY AUTOINCREMENT,
	MMID INTEGER,
	CDCtrim TEXT,
	minYr INTEGER,
	maxYr INTEGER
);